[versions]
mariadb = "3.5.1"
hikaricp = "6.2.0"
lettuce = "7.2.1.RELEASE"
commons-pool2 = "2.13.1"

[libraries]
mariadb-client = { group = "org.mariadb.jdbc", name = "mariadb-java-client", version.ref = "mariadb" }
hikaricp = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikaricp" }
lettuce-core = { group = "io.lettuce", name = "lettuce-core", version.ref = "lettuce" }
commons-pool2 = { group = "org.apache.commons", name = "commons-pool2", version.ref = "commons-pool2" }
